services:
  db:
    image: mysql:9
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      retries: 30
      start_period: 30s

  bank-service:
    build:
      context: ./bank-service
      dockerfile: Dockerfile
    container_name: bank-service
    restart: always
    ports:
      - '5000:5000'
    entrypoint: ['bash', entrypoint.sh]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - bank-service/.env  

  rabbit:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
        - "5672:5672"
  mongodb:
    image: mongo:8.0-noble
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/var/lib/mongodb

  log-service:
    build:
      context: ./log-service
      dockerfile: Dockerfile
    container_name: log-service
    restart: always
    ports:
      - '8000:8000'
    entrypoint: ['bash', entrypoint.sh]
    depends_on:
      - bank-service
      - mongodb
      
volumes:
  db-data:
  mongodb-data:
