services:
  db:
    image: mysql:9
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      retries: 30
      start_period: 30s

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - '5000:5000'
    entrypoint: ['bash', entrypoint.sh]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  

volumes:
  db-data:
